// Copyright 2026 Google LLC

/**
 * ProjectReport — the aggregated output of a full code review run.
 *
 * Lives in the Core layer. Produced by RunCodeReview, consumed by IReportBuilder.
 */

import type { ReviewFinding } from "./ReviewFinding.js";

// ─────────────────────────────────────────────────────────────────────────────
// Supporting types
// ─────────────────────────────────────────────────────────────────────────────

export type SecretSeverity = "critical" | "high";
export type InfraSeverity = "critical" | "high" | "medium" | "low";

export interface SecretFindingEntity {
  file: string;
  line: number;
  patternType: string;
  label: string;
  snippet: string;
  severity: SecretSeverity;
}

export interface InfraFindingEntity {
  file: string;
  line?: number;
  category: string;
  title: string;
  description: string;
  remediation: string;
  severity: InfraSeverity;
}

/**
 * CodeRabbit-style three-paragraph executive summary.
 * Generated by the AI after all findings are aggregated.
 */
export interface ExecutiveSummary {
  /** What this codebase does; quality & technology overview. */
  what: string;
  /** Downstream effects of the top findings on users / other modules. */
  impact: string;
  /** Top 1–3 security or architectural concerns before production. */
  risk: string;
  /** True when IaC exposure heuristics detected internet-facing infra. */
  isPublicFacing: boolean;
}

/**
 * Supplementary AI-generated sub-scores from code-review batches.
 * These are display metrics alongside the deterministic overall score.
 */
export interface AiSubScores {
  namingConventionScore?: number;
  solidPrinciplesScore?: number;
  codeDuplicationPercentage?: number;
  cyclomaticComplexity?: number;
  maintainabilityIndex?: number;
}

/**
 * Timing telemetry for each phase of the review pipeline.
 * All durations are in milliseconds.
 */
export interface TimingStats {
  /** Total wall-clock time for the entire review run. */
  totalMs: number;
  /** File scanning + hashing phase. */
  scanMs: number;
  /** All auditors (secrets, infra, etc.). */
  auditMs: number;
  /** Shallow oneshot global-metrics scan. */
  shallowReviewMs: number;
  /** Sum of all deep chunk review calls. */
  deepReviewMs: number;
  /** Executive summary generation. */
  summaryMs: number;
  /** Number of deep chunks processed. */
  deepChunkCount: number;
  /** Timestamp when the review was run. */
  timestamp: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// ProjectReport — the complete aggregated review output
// ─────────────────────────────────────────────────────────────────────────────

/**
 * ProjectReport — the full review result handed to the presentation layer.
 *
 * Produced incrementally during RunCodeReview and consumed by MarkdownReportBuilder.
 */
export interface ProjectReport {
  /** AI-generated code findings (filtered, de-duped). */
  codeFindings: ReviewFinding[];
  /** Locally-detected hardcoded secrets. */
  secretFindings: SecretFindingEntity[];
  /** IaC/SCA findings from the infrastructure auditor. */
  infraFindings: InfraFindingEntity[];
  /** Whether any IaC file signals internet-facing exposure. */
  isPublicFacing: boolean;
  /** Files audited by the infrastructure auditor. */
  infraScannedFiles: string[];
  /** AI prose summary (optional — skipped if Gemini call fails). */
  executiveSummary?: ExecutiveSummary;
  /** Supplementary AI sub-scores (optional). */
  aiSubScores?: AiSubScores;
  /**
   * SHA-256 hashes of all reviewed files.
   * Used by the incremental review cache to skip unchanged files.
   */
  fileHashes: Record<string, string>;
  /** Pipeline timing telemetry. */
  timingStats?: TimingStats;
}
